# 1. RDS Credentials

resource "aws_secretsmanager_secret" "rds_creds" {
  name = "${var.project}/rds-oltp-credentials"
}

resource "aws_secretsmanager_secret_version" "rds_creds" {
  secret_id = aws_secretsmanager_secret.rds_creds.id
  secret_string = jsonencode({
    username = var.db_username
    password = var.db_password
    host     = aws_db_instance.olist_oltp.address
    port     = 5432
    dbname   = "olist"
  })
}

# 2. GitHub Deploy Key 

resource "aws_secretsmanager_secret" "github_deploy_key" {
  name = "${var.project}/github-dbt-deploy-key"
}

resource "aws_secretsmanager_secret_version" "github_deploy_key" {
  secret_id     = aws_secretsmanager_secret.github_deploy_key.id
  secret_string = jsonencode({
    private_key = "REPLACE_OUT_OF_BAND_VIA_AWS_CLI_OR_CONSOLE"
    repo_url    = "git@github.com:your-org/olist_ecommerce.git"
  })

  lifecycle {
    ignore_changes = [secret_string]
  }
}

# 3. Snowflake Credentials 

resource "aws_secretsmanager_secret" "snowflake_creds" {
  name = "${var.project}/snowflake-credentials"
}

resource "aws_secretsmanager_secret_version" "snowflake_creds" {
  secret_id     = aws_secretsmanager_secret.snowflake_creds.id
  secret_string = jsonencode({
    account   = "REPLACE_ME"
    user      = "REPLACE_ME"
    password  = "REPLACE_ME"
    role      = "REPLACE_ME"
    warehouse = "REPLACE_ME"
    database  = "REPLACE_ME"
  })

  lifecycle {
    ignore_changes = [secret_string]
  }
}


# 4. Airbyte Configuration 
resource "aws_secretsmanager_secret" "airbyte_config" {
  name = "${var.project}/airbyte-config"
}

resource "aws_secretsmanager_secret_version" "airbyte_config" {
  secret_id     = aws_secretsmanager_secret.airbyte_config.id
  secret_string = jsonencode({
    private_ip    = "REPLACE_AFTER_TERRAFORM_APPLY"
    workspace_id = "REPLACE_FROM_AIRBYTE_UI"
  })

  lifecycle {
    ignore_changes = [secret_string]
  }
}

resource "aws_secretsmanager_secret" "airbyte_admin_creds" {
  name        = "${var.project}/airbyte-admin-credentials"
  description = "Airbyte webapp admin login (generated by abctl local install)"
}

resource "aws_secretsmanager_secret_version" "airbyte_admin_creds" {
  secret_id = aws_secretsmanager_secret.airbyte_admin_creds.id
  secret_string = jsonencode({
    email    = "REPLACEME"
    password = "REPLACEME"
  })

  lifecycle {
    ignore_changes = [secret_string] # so re-applies don't clobber a rotated password
  }
}